config/routes.rb
Spirit::Wiki::Engine.routes.draw do
  resources :pages, path: 'wiki' do
    collection do
      get :recent
      post :preview
    end
    member do
      get :comments
    end
  end

  namespace :admin do
    resources :pages, path: 'wiki' do
      resources :versions, controller: :page_versions do
        member do
          post :revert
        end
      end
    end
  end
end

app/models/page.rb
class Page < ApplicationRecord
  include MarkdownBody
  include Searchable

  counter :hits, default: 0

  second_level_cache expires_in: 2.weeks

  has_many :versions, class_name: 'PageVersion'

  attr_accessor :user_id, :change_desc, :version_enable

  validates :slug, :title, :body, presence: true
  # 当需要记录版本时，如果是更新，那么要求填写 :change_desc
  validates :user_id, if: proc { |p| p.version_enable == true }, presence: true
  validates :change_desc, if: proc { |p| p.version_enable == true && !p.new_record? }, presence: true
  validates :slug, format: /\A[a-z0-9\-_]+\z/
  validates :slug, uniqueness: true

  before_save :append_editor
  def append_editor
    unless editor_ids.include?(user_id.to_i)
      editor_ids << user_id.to_i
    end
  end

  # 记录更新版本
  after_save :create_version
  def create_version
    # 只有当 version_enable 为 true 的时候才记录版本
    # 以免后台，以及其他的一些 update 时被误调用
    return true unless version_enable
    # 只有 body, title, slug 更改了才更新版本
    if self.body_changed? || self.title_changed? || self.slug_changed?
      update_column(:version, self.version + 1)
      PageVersion.create(user_id: user_id,
                         page_id: id,
                         desc: change_desc || '',
                         version: version,
                         body: body,
                         title: title,
                         slug: slug)
    end
  end

  def as_indexed_json(_options = {})
    as_json(only: [:slug, :title, :body])
  end

  def indexed_changed?
    slug_changed? || title_changed? || body_changed?
  end

  def to_param
    slug
  end

  # 撤掉到指定版本
  def revert_version(version)
    page_version = PageVersion.where(page_id: id, version: version).first
    return false if page_version.blank?
    update(body: page_version.body,
           title: page_version.title,
           slug: page_version.slug)
  end

  def editors
    User.where(id: editor_ids)
  end

  def self.find_by_slug(slug)
    fetch_by_uniq_keys(slug: slug)
  end
end

app/models/page_version.rb
class PageVersion < ApplicationRecord
  include MarkdownBody

  belongs_to :user
  belongs_to :page
end

app/models/spirit/wiki/ability.rb
module Spirit::Wiki
  class Ability
    include CanCan::Ability

    attr_reader :user

    def initialize(u)
      @user = u
      if @user.blank?
        roles_for_anonymous
      elsif @user.roles?(:admin)||@user.roles?(:super_admin)
        can :manage, Page
      elsif @user.roles?(:wiki_editor)
        roles_for_wiki_editor
      else
        roles_for_anonymous
      end
    end

    protected

    def roles_for_wiki_editor
      can :create, Page
      can :update, Page, locked: false
    end

    def roles_for_anonymous
      can [:read, :recent, :preview, :comments], Page
    end
  end
end

app/models/spirit/wiki/application_record.rb
module Spirit::Wiki
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/controllers/spirit/wiki/admin/page_versions_controller.rb
module Spirit::Wiki::Admin
  class PageVersionsController < ::Admin::ApplicationController
    def index
      @page = Page.find(params[:page_id])
      @page_versions = @page.versions.order(version: :desc).page(params[:page])
    end

    def show
      @page = Page.find(params[:page_id])
      @page_version = @page.versions.find(params[:id])
    end

    def revert
      @page = Page.find(params[:page_id])
      @page_version = @page.versions.find(params[:id])
      if @page.revert_version(@page_version.version)
        redirect_to admin_page_versions_path(params[:page_id]), notice: "Wiki 内容已经撤销到了版本 #{@page_version.version}"
      else
        redirect_to admin_page_versions_path(params[:page_id]), alert: "版本撤销失败，原因: #{@page.errors.full_messages.join('<br />')}"
      end
    end
  end
end

app/controllers/spirit/wiki/admin/pages_controller.rb
module Spirit::Wiki::Admin
  class PagesController < ::Admin::ApplicationController
    before_action :set_page, only: [:show, :edit, :update, :destroy]

    def index
      @pages = Page.unscoped.order(id: :desc).page(params[:page])
    end

    def edit
    end

    def update
      @page.title = params[:page][:title]
      @page.body = params[:page][:body]
      @page.slug = params[:page][:slug]
      @page.locked = params[:page][:locked]
      @page.user_id = current_user.id

      if @page.save
        redirect_to(admin_pages_path, notice: 'Page was successfully updated.')
      else
        render action: 'edit'
      end
    end

    def destroy
      if @page.deleted_at.present?
        @page.delete
      else
        @page.destroy
      end

      redirect_to(admin_pages_path)
    end

    private

    def set_page
      @page = Page.unscoped.find_by_slug(params[:id])
    end
  end
end

app/controllers/spirit/wiki/application_controller.rb
module Spirit::Wiki
  class ApplicationController < ::ApplicationController
    helper ApplicationHelper

    def current_ability
      @current_ability ||= Spirit::Wiki::Ability.new(current_user)
    end
  end
end

app/controllers/spirit/wiki/pages_controller.rb
module Spirit::Wiki
  class PagesController < Spirit::Wiki::ApplicationController
    require_module_enabled! :wiki
    before_action :set_page, only: [:show, :edit, :update, :destroy, :comments]

    etag { Setting.wiki_sidebar_html }

    def index
      fresh_when(Setting.wiki_index_html)
    end

    def recent
      @pages = Page.recent.page(params[:page])
      fresh_when(@pages)
    end

    def show
      if @page.blank?
        if current_user.blank?
          render_404
          return
        end

        redirect_to new_page_path(title: params[:id]), notice: 'Page not Found, Please create a new page'
        return
      end

      @page.hits.incr(1)
      fresh_when(@page)
    end

    def comments
      render_404 if @page.blank?
    end

    def new
      authorize! :create, Page

      @page = Page.new
      @page.slug = params[:title]
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @page }
      end
    end

    def edit
      authorize! :edit, @page
    end

    def create
      authorize! :create, Page

      @page = Page.new(page_params)
      @page.user_id = current_user.id
      @page.version_enable = true

      if @page.save
        redirect_to page_path(@page.slug), notice: t('common.create_success')
      else
        render action: 'new'
      end
    end

    def update
      authorize! :update, @page

      @page.version_enable = true
      @page.user_id = current_user.id

      if @page.update(page_params)
        redirect_to page_path(@page.slug), notice: t('common.update_success')
      else
        render action: 'edit'
      end
    end

    def preview
      render plain: Spirit::Markdown.call(params[:body])
    end

    protected

    def set_page
      @page = Page.find_by_slug(params[:id])
    end

    def page_params
      params.require(:page).permit(:title, :body, :slug, :change_desc)
    end
  end
end

app/helpers/spirit/wiki/application_helper.rb
module Spirit::Wiki
  module ApplicationHelper
    delegate :comments_path, to: :main_app

    def page_title_tag(page)
      return '' if page.blank?
      link_to(page.title, page_path(page.slug), class: 'page')
    end
  end
end

app/views/layouts/spirit/wiki/application.html.erb
<% content_for :stylesheets do %>
  <%= stylesheet_link_tag    "spirit/wiki/application", media: "all" %>
<% end %>

<% content_for :javascripts do %>
  <%= javascript_include_tag "spirit/wiki/application" %>
<% end %>

<% content_for :main do %>
  <div id="spirit-wiki">
    <%= yield %>
  </div>
<% end %>

<%= render template: "/layouts/application" %>

app/views/spirit/wiki/admin/page_versions/index.html.erb
<% content_for :sitemap do %>
  <a href="<%= admin_pages_path %>">Wiki</a> <i class="fa fa-angle-right"></i>
  <a href="<%= admin_page_path(params[:page_id]) %>">Page:<%= params[:page_id] %></a> <i class="fa fa-angle-right"></i>
  <span class="current">版本历史</span>
<% end %>
<h1>Wiki 列表</h1>

<table class="table table-bordered table-striped table-condensed">
  <tr class="head">
    <td class="first">Version</td>
    <td style="width:200px">Slug</td>
    <td>Title</td>
    <td>Desc</td>
    <td>Creator</td>
    <td>At</td>
    <td></td>
  </tr>

<% @page_versions.each do |item| %>
  <tr>
    <td class="first"><%= item.version %></td>
    <td><%= item.slug %></td>
    <td><%= item.title %></td>
    <td><%= item.desc %></td>
    <td><%= user_name_tag(item.user) %></td>
    <td><%= l item.created_at, format: :long %></td>
    <td><%= link_to 'View', admin_page_version_path(item.page_id, item.id) %>
    <%= link_to 'Revert', revert_admin_page_version_path(item.page_id, item.id), 'data-confirm' => 'Are you sure?', method: :post %></td>
  </tr>
<% end %>
</table>
<%= paginate @page_versions %>

app/views/spirit/wiki/admin/page_versions/show.html.erb
<% content_for :sitemap do %>
  <a href="<%= admin_pages_path %>">Wiki</a> <i class="fa fa-angle-right"></i>
  <a href="<%= edit_admin_page_path(params[:page_id]) %>">Page:<%= params[:page_id] %></a> <i class="fa fa-angle-right"></i>
  <a href="<%= admin_page_versions_path(params[:page_id]) %>">版本历史</a> <i class="fa fa-angle-right"></i>
  <span class="current">明细</span>
<% end %>
<div class="pull-right">
  <%= link_to 'Revert', revert_admin_page_version_path(@page_version.page_id, @page_version.id), 'data-confirm' => 'Are you sure?', method: :post, class: "btn btn-danger" %>
</div>
<div class="field">
  <%= user_name_tag @page_version.user %> 修改与 <%= l @page_version.created_at, format: :long %>
</div>
<div class="field">
  Slug: <%= @page_version.slug %>
</div>
<div class="field">
  Title: <%= @page_version.title %>
</div>

<%= @page_version.body_html %>

app/views/spirit/wiki/admin/pages/_form.html.erb
<%= simple_form_for([:admin,@page]) do |f| %>
  <%= render "shared/error_messages", target: @page %>
  <fieldset>
    <legend>Wiki页面编辑</legend>
    <%= f.input :locked, as: :boolean, hint: "锁定后，前台非管理员将无法修改。" %>
    <%= f.input :slug %>
    <%= f.input :title, input_html: { class: "xxlarge" } %>
    <%= f.input :body, as: :text, input_html: { class: "span8", rows: "30"} %>
    <div class="form-actions">
      <%= f.submit t("common.save"), class: "btn btn-primary", 'data-disable-with' => t("common.saving") %>
    </div>
<% end %>

app/views/spirit/wiki/admin/pages/edit.html.erb
<% content_for :sitemap do %>
  <a href="<%= admin_pages_path %>">Wiki</a> <i class="fa fa-angle-right"></i> <span class="current">修改</span>
<% end %>
<h1>Editing page</h1>

<%= render 'form' %>

app/views/spirit/wiki/admin/pages/index.html.erb
<% content_for :sitemap do %>
  <span class="current">Wiki</span>
<% end %>

<table class="table table-bordered table-striped table-condensed">
  <tr class="head">
    <td class="first">ID</td>
    <td style="width:200px">Slug</td>
    <td>Title</td>
    <td>at</td>
    <td>lock</td>
    <td>Version</td>
    <td style="width:80px;"></td>
  </tr>

<% @pages.each do |page| %>
  <tr class="<%= 'deleted' if !page.deleted_at.blank? %>">
    <td class="first"><%= page.id %></td>
    <td><%= page.slug %></td>
    <td><%= truncate(page.title, length: 30) %></td>
    <td><%= l page.created_at, format: :short %></td>
    <td><%= page.locked %></td>
    <td><%= page.version %></td>
    <td>
      <%= link_to '', admin_page_versions_path(page.id), class: "fa fa-clock-o", title: "修改记录" %>
    <%= link_to '', edit_admin_page_path(page), class: "fa fa-pencil" %>
    <%= link_to '', admin_page_path(page), 'data-confirm' => 'Are you sure?', method: :delete, class: "fa fa-trash" %></td>
  </tr>
<% end %>
</table>
<%= paginate @pages %>

app/views/spirit/wiki/pages/_form.html.erb
<%= simple_form_for @page do |f| %>
  <%= render "shared/error_messages", target: @page %>

  <%= f.input :slug, hint: "#{Setting.base_url}/wiki/:slug"%>
  <%= f.input :title, input_html: { class: "xxlarge" } %>

  <div class="edit-tools">
    <%= render "/shared/editor_toolbar" %>
  </div>

  <div class="form-group">
    <%= f.text_area :body, rows: 30, class: 'form-control spirit-editor' %>
    <p class="help-block">
      请使用 Markdown 格式编写,可以试试用 <a href='https://www.typora.io' target='_blank'>Typora</a> 这个 App 来编写。
    </p>
  </div>

  <% if not @page.new_record? %>
    <%= f.input :change_desc, as: :text, input_html: { rows: "2" }, hint: t("pages.describe_this_time_change") %>
  <% end %>
  <div class="form-group">
    <%= f.submit t("common.save"), class: "btn btn-primary", 'data-disable-with' => t("common.saving") %>
    <%= link_to t("common.cancel"), pages_path, class: "btn btn-default reset" %>
  </div>
<% end %>

app/views/spirit/wiki/pages/_sidebar.html.erb
<div class="sidebar wiki-sidebar col-sm-3">
  <div class="panel panel-default">
    <div class="panel-body">
      <strong>导航</strong>
      <ul>
        <li><a href="/wiki">首页</a></li>
        <li><%= link_to(t("pages.wiki_index"), recent_pages_path) %></li>
        <li class="hide-ios"><%= link_to(t("pages.new_page"), new_page_path)%></li>
      </ul>

      <%= raw Setting.wiki_sidebar_html %>
    </div>
  </div>
</div>

app/views/spirit/wiki/pages/comments.html.erb
<% title_tag [t('pages.comments'), @page.title].join(' · ') %>

<div class="row">
  <div class="hide-ios">
    <%= render 'sidebar' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div id="comments" class="panel-body">
        《<%= link_to @page.title, page_path(@page.slug) %>》 - <%= t('pages.comments') %>
      </div>
    </div>

    <div class="hide-ios">
      <%= render "/shared/comments", commentable: @page %>
    </div>
  </div>
</div>

app/views/spirit/wiki/pages/edit.html.erb
<% title_tag t("pages.edit_page") %>

<div class="panel panel-default">
  <div class="panel-heading"><%= t("pages.edit_page") %></div>
  <div class="panel-body">
    <%= render "form" %>
  </div>
</div>

app/views/spirit/wiki/pages/index.html.erb
<% title_tag t("menu.wiki") %>

<div class="row">
  <%= render 'sidebar' %>
  <% if !turbolinks_app? %>
    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-body">
          <%= raw Setting.wiki_index_html %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/spirit/wiki/pages/new.html.erb
<% title_tag t("pages.edit_page") %>

<div class="panel panel-default">
  <div class="panel-heading"><%= t("pages.new_page")%></div>
  <div class="panel-body">
    <%= render "form" %>
  </div>
</div>

app/views/spirit/wiki/pages/recent.html.erb
<% title_tag t('pages.wiki_index') %>

<div class="row">
  <div class="hide-ios">
    <%= render 'sidebar' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading hide-ios"><%= t('pages.wiki_index') %></div>
      <div class="panel-body">
        <ul>
          <% @pages.each do |item| %>
            <li><%= page_title_tag(item) %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/spirit/wiki/pages/show.html.erb
<% title_tag @page.title %>

<div class="row">
  <div class="hide-ios">
    <%= render 'sidebar' %>
  </div>
  <div class="col-md-9 page-detail">
    <div class="panel panel-default">
      <% if !@page.locked or admin? %>
        <div class="panel-heading">
          <h1><%= @page.title %></h1>
          <div class="infos">
            <%= link_to comments_page_path(@page.slug) do %>
              <%= @page.comments_count %> 条评论
            <% end %>,
            <%= @page.version %> 次修正，<%= @page.hits.to_s %> 次阅读， <%= t("common.last_modified_at")%> <%= timeago(@page.updated_at) %>
            <span class="pull-right opts hide-ios">
              <%= link_to(icon_tag('pencil'), edit_page_path(@page)) if can? :edit, @page %>
            </span>
          </div>
        </div>

      <% end %>

      <div class="panel-body markdown markdown-toc">
        <article>
          <%= @page.body_html %>
        </article>
      </div>

      <div class="editors panel-footer clearfix">
        <div class="heading">
          <%= t("pages.wiki_page_contributors")%>
          <span class="pull-right"><%= social_share_button_tag h("#{@page.title} via: @#{Setting.twitter_id} ") %></span>
        </div>
        <div class="avatars">
          <% @page.editors.each do |item| %>
            <%= user_avatar_tag(item, :xs) %>
          <% end %>
        </div>
        <div class="buttons hide-ios">
          <%= link_to "发表评论", comments_page_path(@page.slug, anchor: "new_comment"), class: "btn btn-success" %>
        </div>
      </div>
    </div>
  </div>
</div>